using System.Text.Json;

namespace R2WAI.Application.Features.KnowledgeBases.Commands;

internal class KnowledgeBaseConfigSnapshot
{
    public string Name { get; init; } = string.Empty;
    public string? Description { get; init; }
    public string? EmbeddingModel { get; init; }
    public int? ChunkSize { get; init; }
    public int? ChunkOverlap { get; init; }
    public string? VectorCollectionName { get; init; }
    public List<KnowledgeBaseSourceSnapshotItem> Sources { get; init; } = [];
}

internal class KnowledgeBaseSourceSnapshotItem
{
    public string Type { get; init; } = string.Empty;
    public Guid? ReferenceId { get; init; }
    public string? Url { get; init; }
    public string? Content { get; init; }
}

/// <summary>
/// Builds the JSON snapshot stored on a <see cref="KnowledgeBaseVersion"/> and restores it back onto a
/// live <see cref="KnowledgeBase"/> during rollback. Shared by <see cref="CreateKnowledgeBaseVersionCommandHandler"/>
/// and <see cref="RollbackKnowledgeBaseVersionCommandHandler"/> so both always snapshot the same shape
/// — mirrors ApplicationVersionSnapshotService's role for ApplicationVersion. Only configuration
/// (what defines the KB) is captured — not runtime indexing state (Status/ChunkCount/IndexedAt/Error),
/// which is regenerated by re-indexing after a rollback, not restored from history.
/// </summary>
internal static class KnowledgeBaseVersionSnapshotService
{
    public static async Task<string> BuildSnapshotJsonAsync(
        KnowledgeBase knowledgeBase,
        IRepository<KnowledgeBaseSource> sourceRepo,
        CancellationToken cancellationToken)
    {
        var sources = await sourceRepo.FindAsync(s => s.KnowledgeBaseId == knowledgeBase.Id, cancellationToken);

        var snapshot = new KnowledgeBaseConfigSnapshot
        {
            Name = knowledgeBase.Name,
            Description = knowledgeBase.Description,
            EmbeddingModel = knowledgeBase.EmbeddingModel,
            ChunkSize = knowledgeBase.ChunkSize,
            ChunkOverlap = knowledgeBase.ChunkOverlap,
            VectorCollectionName = knowledgeBase.VectorCollectionName,
            Sources = sources.Select(s => new KnowledgeBaseSourceSnapshotItem
            {
                Type = s.Type,
                ReferenceId = s.ReferenceId,
                Url = s.Url,
                Content = s.Content
            }).ToList()
        };

        return JsonSerializer.Serialize(snapshot);
    }

    public static KnowledgeBaseConfigSnapshot Deserialize(string configSnapshotJson) =>
        JsonSerializer.Deserialize<KnowledgeBaseConfigSnapshot>(configSnapshotJson)
            ?? throw new InvalidOperationException("Stored knowledge base version snapshot could not be read.");
}
