global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using MediatR;
global using Microsoft.Extensions.Logging;
global using AutoMapper;
global using R2WAI.Domain.Entities;
global using R2WAI.Domain.Enums;
global using R2WAI.Domain.Interfaces;
global using R2WAI.Application.Common.Models;
global using NotFoundException = R2WAI.Application.Common.Exceptions.NotFoundException;
global using UnauthorizedException = R2WAI.Application.Common.Exceptions.UnauthorizedException;
global using ValidationException = R2WAI.Application.Common.Exceptions.ValidationException;
global using R2WAI.Application.Common.Interfaces;
global using R2WAI.Application.Features.Chat.DTOs;
global using R2WAI.Application.Features.Documents.DTOs;
global using R2WAI.Application.Features.KnowledgeBases.DTOs;
global using R2WAI.Application.Features.Chatbots.DTOs;
global using R2WAI.Application.Features.Workflows.DTOs;
global using R2WAI.Application.Features.Assistants.DTOs;
global using R2WAI.Application.Features.Admin.DTOs;
global using R2WAI.Application.Features.Integrations.DTOs;
global using R2WAI.Application.Features.Operations.DTOs;
global using R2WAI.Application.Features.Proposals.DTOs;
